import { ElementRef, EventEmitter, OnInit } from '@angular/core';
import { MaDataGridColumnOptions, MaDataGridHeadFilter } from '../../interfaces/ma-data-grid-options';
import * as i0 from "@angular/core";
export declare class DataGridOpFilterComponent implements OnInit {
    private document;
    value: string;
    col: MaDataGridColumnOptions;
    elemToggle: ElementRef;
    elemValue: ElementRef;
    changeOperator: EventEmitter<any>;
    changeEmptyOperator: EventEmitter<any>;
    options: any;
    multiple: boolean;
    isRowHTML: boolean;
    values: MaDataGridHeadFilter[];
    label: string;
    popupPosition: any;
    constructor(document: Document);
    getFuncClickDocument(): () => void;
    toggleDiv(): void;
    ngOnInit(): void;
    setFirstChoice(): void;
    getOperator(): any;
    changeValues(opt: any): void;
    getConditions(filter_value: any): any[];
    changeValue(opt: any, ignoreToggle?: boolean): void;
    _changeOperator(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<DataGridOpFilterComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<DataGridOpFilterComponent, "ma-data-grid-op-filter", never, { "value": "value"; "col": "col"; }, { "changeOperator": "changeOperator"; "changeEmptyOperator": "changeEmptyOperator"; }, never, never>;
}
